In [19]:
import numpy as np
import pandas as pd
from IPython.display import display

In [3]:
import io
import pandas as pd

# 1. Define your CSV string
csv_string = """Name,Age,City
Alice,25,New York
Bob,30,Los Angeles
Charlie,35,Chicago"""

# 2. Convert string to a file-like object and read it
df = pd.read_csv(io.StringIO(csv_string))
        
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [4]:
tips_df = pd.read_csv('tips.csv')
tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [6]:
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [7]:
tips_df = pd.read_csv('tips.csv')
print(tips_df.columns)
print(tips_df.index)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')
RangeIndex(start=0, stop=244, step=1)

In [37]:
# from IPython.display import display
tips_df = pd.read_csv('tips.csv')
print(len(tips_df))
print()
display('head', tips_df.head())
print()
display(tips_df.tail(5))

244

'head'

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [22]:
tips_df = pd.read_csv('tips.csv')
tips_df.describe().transpose()
# percentile
#      3        15       23        31
# 1, 2, 8, 9, 14, 20, 22, 25, 29, 30

#      3          26       27.5          31
# 1, 2, 23, 24, 25, 26, 27,   28, 29, 30

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [29]:
tips_df = pd.read_csv('tips.csv')
display('1 column = series', tips_df['tip'])  # display(tips_df['tip'].to_frame())
print()
display('2 columns = df', tips_df[ ['tip', 'day'] ])

'1 column = series'

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

'2 columns = df'

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [52]:
tips_df = pd.read_csv('tips.csv')
tips_df['Sum With Tip'] = tips_df['tip'] + tips_df['total_bill']
tips_df['tip'] = tips_df['tip']  * 2
tips_df.drop('tip', axis=1, inplace=True)  # deleted column 'tip'
tips_df.drop(1, axis=0, inplace=True)  # deleted row 0 -- index 1
tips_df
# create column called "Tip Percentage" i.e. 300 and put 30 => 10

,total_bill,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Sum With Tip
0,16.99,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,18.00
2,21.01,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,24.51
3,23.68,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,26.99
4,24.59,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,28.20
5,25.29,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679,30.00
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,34.95
240,27.18,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,29.18
241,22.67,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,24.67
242,17.82,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,19.57
243,18.78,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,21.78

In [65]:
df = pd.read_csv('tips.csv')
df = df.set_index('Payer Name')
df = df.drop('Michael Avila', axis=0)  # drop by index 
df.reset_index()

,Payer Name,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
0,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959
1,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
2,Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
3,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
4,Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,Kimberly Crane,35.83,4.67,Female,No,Sat,Dinner,3,11.94,676184013727,Sat9777
239,Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565404,Sat1766
240,Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747196,Sat3880
241,Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17
242,Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698139,Thur672

In [67]:
df = pd.read_csv('tips.csv')
df = df.set_index('Payer Name')
df.loc['Michael Avila']  # by key
# df = df.drop('Michael Avila', axis=0)  # drop by index 
#df.reset_index()

# make 'Payment ID' as index
# display all rows with Sun2959
# reset the index
# set index as 'time'
# display all rows with index 'Dinner'
# drop all rows with index Dinner
# drop column smoker
# display df

total_bill                     29.03
tip                             5.92
sex                             Male
smoker                            No
day                              Sat
time                          Dinner
size                               3
price_per_person                9.68
CC Number           5296068606052842
Payment ID                   Sat2657
Name: Michael Avila, dtype: object

In [85]:
df = pd.read_csv('tips.csv')
df = df.set_index('Payer Name')

# loc  --> index
# iloc --> the i row

df.iloc[0:5]
df.iloc[4::-1]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959

In [81]:
df = pd.read_csv('tips.csv')
df = df.set_index('Payer Name')
display(df.loc['Douglas Tucker': 'Tonya Carter'])  # like df.iloc[4:0:-1]
display(df.loc[ ['Douglas Tucker', 'Tonya Carter'] ])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251

In [ ]:
# load tips csv 
# make 'payment id' as index
# display
# display the first 5 using loc, and the first 5, using iloc
# display the first 5 in reverse, using iloc